### PR TITLE
Added overview to Basic VCS in README.md

### PR DESCRIPTION
**Pull request by kishore-narendran**

### CODE REVIEW

**Comment by sigit-prayoga** [comment]
All good, let's merge!

**Comment by mhaidarhanif** [comment]
@kishore-narendran Thank you for migrating the data from the spreasheet.
@sigit-prayoga Alright.

**Comment by mhaidarhanif** [comment]
Maybe I will edit some minor editing style. Because in Markdown, there is a code syntax like `branch` not  just -branch. I actually have updated them in the newer version of our spreadsheet, but not the public copy yet.

**Comment by mhaidarhanif** [comment]
Almost forgot. Should we omit the Duration?

**Comment by kishore-narendran** [comment]
@mhaidarh : I'll make those changes, don't worry about it. And I will submit samples in a few days. Have a look

**Comment by kishore-narendran** [comment]
And, I think you should omit the duration.

**Comment by mhaidarhanif** [comment]
@kishore-narendran Thank you very much!
hahah I actually planned to edit them tonight, but I should have a rest right now.

**Comment by sigit-prayoga** [comment]
should we? isn't it very helpful to decide viewer's time prediction? or we just need to view the total hours?

**Comment by mhaidarhanif** [comment]
Because everyone would have a variance of pace time, actually.

**Comment by kishore-narendran** [comment]
And furthermore, it doesn't significantly help. A good addition is to have a course completion checklist. WHat do you guys think?

**Comment by mhaidarhanif** [comment]
Right, a completion checklist. I just realized that.
I actually prefer that. So anyone can estimate the required time for each learning portion.

Btw probably in a general sense, we should do the discussion about all three repos here.
Unless there's something specific.

**Comment by kishore-narendran** [comment]
I have updated code syntax in 413d682b521a154722d6ff7e818d7af78234d593
And have issued a pull request https://github.com/agnium/agnium-basic-vcs/pull/2

**Comment by mhaidarhanif** [comment]
Thanks!

**Pull request merged**
